# Generated by Django 5.0 on 2024-01-20 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='tbl_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=100)),
                ('pswd', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
                ('start_price', models.CharField(default='', max_length=100)),
                ('offer', models.CharField(default='', max_length=100)),
                ('category_url', models.CharField(default='', max_length=100)),
                ('qr_image_path', models.ImageField(default='image/null.png', upload_to='image')),
                ('floor', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=100)),
                ('phn', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('uname', models.CharField(default='', max_length=100)),
                ('pswd', models.CharField(default='', max_length=100)),
                ('adrs', models.CharField(default='', max_length=100)),
                ('plc', models.CharField(default='', max_length=100)),
                ('licence_num', models.CharField(default='', max_length=100)),
                ('utype', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('is_online', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('brand', models.CharField(default='', max_length=100)),
                ('model', models.CharField(default='', max_length=100)),
                ('actual_price', models.CharField(default='', max_length=100)),
                ('our_price', models.CharField(default='', max_length=100)),
                ('discount', models.CharField(default='', max_length=100)),
                ('other_offers', models.CharField(default='', max_length=100)),
                ('size', models.CharField(default='', max_length=100)),
                ('color', models.CharField(default='', max_length=100)),
                ('warranty', models.CharField(default='', max_length=100)),
                ('desc', models.CharField(default='', max_length=1000)),
                ('instock', models.CharField(default='', max_length=100)),
                ('section', models.CharField(default='', max_length=1000)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Eshopapp.tbl_category')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_products_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.IntegerField(blank=True, default=0, null=True)),
                ('feedback', models.CharField(default='', max_length=100)),
                ('date', models.CharField(default='', max_length=100)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Eshopapp.tbl_products')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Eshopapp.tbl_register')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_feedback_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(default='', max_length=100)),
                ('ratings', models.IntegerField(blank=True, default=0, null=True)),
                ('date', models.CharField(default='', max_length=100)),
                ('salesman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesman_feedback_ratings', to='Eshopapp.tbl_register')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_feedback_ratings', to='Eshopapp.tbl_register')),
            ],
        ),
        migrations.CreateModel(
            name='salesman_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesmans', to='Eshopapp.tbl_register')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='Eshopapp.tbl_register')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_request_salesman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('categories', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('salesman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocated_requests', to='Eshopapp.tbl_register')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_requests', to='Eshopapp.tbl_register')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Eshopapp.tbl_products')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Eshopapp.tbl_register')),
            ],
        ),
        migrations.CreateModel(
            name='user_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='Eshopapp.tbl_register')),
            ],
        ),
    ]
