# Generated by Django 5.0 on 2024-01-20 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshopapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_notification',
            name='salesman',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, related_name='salesman', to='Eshopapp.tbl_register'),
            preserve_default=False,
        ),
    ]
