# Generated by Django 5.0 on 2024-01-20 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshopapp', '0002_user_notification_salesman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_notification',
            name='salesman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesman', to='Eshopapp.tbl_register'),
        ),
    ]
