# Generated by Django 5.0 on 2024-02-23 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eshopapp', '0003_alter_user_notification_salesman'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
